// Define windows width and height
#define WINDOWS_WIDTH glutGet(GLUT_SCREEN_WIDTH)
#define WINDOWS_HEIGHT glutGet(GLUT_SCREEN_HEIGHT)
#define WINDOWS_CENTER_X WINDOWS_WIDTH / 2
#define WINDOWS_CENTER_Y WINDOWS_HEIGHT / 2

